package cn.Ideal.demo.entity;

public class Ability {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer aid;

    public Ability(Integer aid, Integer aone, Integer atwo, Integer athree, Integer afour, Integer afive, Integer asix, Integer aseven, Integer aeight, Integer anine, Integer aten, Integer aeleven, Integer uid) {
        this.aid = aid;
        this.aone = aone;
        this.atwo = atwo;
        this.athree = athree;
        this.afour = afour;
        this.afive = afive;
        this.asix = asix;
        this.aseven = aseven;
        this.aeight = aeight;
        this.anine = anine;
        this.aten = aten;
        this.aeleven = aeleven;
        this.uid = uid;
    }

    public Ability(int f) {
        this.aone=f;
        this.atwo=f;
        this.athree=f;
        this.afour=f;
        this.afive=f;
        this.asix=f;
        this.aseven=f;
        this.aeight=f;
        this.anine=f;
        this.aten=f;
        this.aeleven=f;
    }

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer aone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer atwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer athree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer afour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer afive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer asix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer aseven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer aeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer anine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aTen
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer aten;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.aEleven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer aeleven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ability.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aId
     *
     * @return the value of ability.aId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aId
     *
     * @param aid the value for ability.aId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aOne
     *
     * @return the value of ability.aOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAone() {
        return aone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aOne
     *
     * @param aone the value for ability.aOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAone(Integer aone) {
        this.aone = aone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aTwo
     *
     * @return the value of ability.aTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAtwo() {
        return atwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aTwo
     *
     * @param atwo the value for ability.aTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAtwo(Integer atwo) {
        this.atwo = atwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aThree
     *
     * @return the value of ability.aThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAthree() {
        return athree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aThree
     *
     * @param athree the value for ability.aThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAthree(Integer athree) {
        this.athree = athree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aFour
     *
     * @return the value of ability.aFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAfour() {
        return afour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aFour
     *
     * @param afour the value for ability.aFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAfour(Integer afour) {
        this.afour = afour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aFive
     *
     * @return the value of ability.aFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAfive() {
        return afive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aFive
     *
     * @param afive the value for ability.aFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAfive(Integer afive) {
        this.afive = afive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aSix
     *
     * @return the value of ability.aSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAsix() {
        return asix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aSix
     *
     * @param asix the value for ability.aSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAsix(Integer asix) {
        this.asix = asix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aSeven
     *
     * @return the value of ability.aSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAseven() {
        return aseven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aSeven
     *
     * @param aseven the value for ability.aSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAseven(Integer aseven) {
        this.aseven = aseven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aEight
     *
     * @return the value of ability.aEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAeight() {
        return aeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aEight
     *
     * @param aeight the value for ability.aEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAeight(Integer aeight) {
        this.aeight = aeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aNine
     *
     * @return the value of ability.aNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAnine() {
        return anine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aNine
     *
     * @param anine the value for ability.aNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAnine(Integer anine) {
        this.anine = anine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aTen
     *
     * @return the value of ability.aTen
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAten() {
        return aten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aTen
     *
     * @param aten the value for ability.aTen
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAten(Integer aten) {
        this.aten = aten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.aEleven
     *
     * @return the value of ability.aEleven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getAeleven() {
        return aeleven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.aEleven
     *
     * @param aeleven the value for ability.aEleven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setAeleven(Integer aeleven) {
        this.aeleven = aeleven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ability.uId
     *
     * @return the value of ability.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ability.uId
     *
     * @param uid the value for ability.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}