package cn.Ideal.demo.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Cid
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private Integer cid;
private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
    private String c;

    public String getC() {
        return c;
    }

    public void setC(String c) {
        this.c = c;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.title
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.tips
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String tips;
    private Integer uid;

    public Integer getUid() {
        return uid;
    }

    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.Ctime
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.count
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private Integer count;
private String cimg;

    public String getCimg() {
        return cimg;
    }

    @Override
    public String toString() {
        return "Comment{" +
                "cid=" + cid +
                ", title='" + title + '\'' +
                ", content='" + content + '\'' +
                ", tips='" + tips + '\'' +
                ", uid=" + uid +
                ", ctime=" + ctime +
                ", count=" + count +
                ", cimg='" + cimg + '\'' +
                '}';
    }

    public void setCimg(String cimg) {
        this.cimg = cimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Cid
     *
     * @return the value of comment.Cid
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Cid
     *
     * @param cid the value for comment.Cid
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.title
     *
     * @return the value of comment.title
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.title
     *
     * @param title the value for comment.title
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.tips
     *
     * @return the value of comment.tips
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.tips
     *
     * @param tips the value for comment.tips
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setTips(String tips) {
        this.tips = tips == null ? null : tips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.Ctime
     *
     * @return the value of comment.Ctime
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.Ctime
     *
     * @param ctime the value for comment.Ctime
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.count
     *
     * @return the value of comment.count
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.count
     *
     * @param count the value for comment.count
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}