package cn.Ideal.demo.entity;

import java.util.Date;

public class Commentvip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.Cid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer cid;
    private User user;
    private String c;

    public String getC() {
        return c;
    }

    public void setC(String c) {
        this.c = c;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**

     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.cimg
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private String cimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.title
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.content
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.tips
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private String tips;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.Ctime
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.count
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentVip.uid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.Cid
     *
     * @return the value of commentVip.Cid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.Cid
     *
     * @param cid the value for commentVip.Cid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.cimg
     *
     * @return the value of commentVip.cimg
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String getCimg() {
        return cimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.cimg
     *
     * @param cimg the value for commentVip.cimg
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setCimg(String cimg) {
        this.cimg = cimg == null ? null : cimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.title
     *
     * @return the value of commentVip.title
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.title
     *
     * @param title the value for commentVip.title
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.content
     *
     * @return the value of commentVip.content
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.content
     *
     * @param content the value for commentVip.content
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.tips
     *
     * @return the value of commentVip.tips
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String getTips() {
        return tips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.tips
     *
     * @param tips the value for commentVip.tips
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setTips(String tips) {
        this.tips = tips == null ? null : tips.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.Ctime
     *
     * @return the value of commentVip.Ctime
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.Ctime
     *
     * @param ctime the value for commentVip.Ctime
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.count
     *
     * @return the value of commentVip.count
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.count
     *
     * @param count the value for commentVip.count
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentVip.uid
     *
     * @return the value of commentVip.uid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentVip.uid
     *
     * @param uid the value for commentVip.uid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}