package cn.Ideal.demo.entity;

public class Info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.iid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer iid;

    @Override
    public String toString() {
        return "Info{" +
                "iid=" + iid +
                ", icontent='" + icontent + '\'' +
                ", pid=" + pid +
                ", updown=" + updown +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.icontent
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private String icontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.updown
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer updown;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.iid
     *
     * @return the value of info.iid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.iid
     *
     * @param iid the value for info.iid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.icontent
     *
     * @return the value of info.icontent
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String getIcontent() {
        return icontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.icontent
     *
     * @param icontent the value for info.icontent
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setIcontent(String icontent) {
        this.icontent = icontent == null ? null : icontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.pid
     *
     * @return the value of info.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.pid
     *
     * @param pid the value for info.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.updown
     *
     * @return the value of info.updown
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getUpdown() {
        return updown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.updown
     *
     * @param updown the value for info.updown
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setUpdown(Integer updown) {
        this.updown = updown;
    }
}