package cn.Ideal.demo.entity;

public class Knowledge {
    public Knowledge(Integer kid, Integer kone, Integer ktwo, Integer kthree, Integer kfour, Integer kfive, Integer ksix, Integer kseven, Integer keight, Integer knine, Integer kten, Integer uid) {
        this.kid = kid;
        this.kone = kone;
        this.ktwo = ktwo;
        this.kthree = kthree;
        this.kfour = kfour;
        this.kfive = kfive;
        this.ksix = ksix;
        this.kseven = kseven;
        this.keight = keight;
        this.knine = knine;
        this.kten = kten;
        this.uid = uid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */

    private Integer kid;
    public Knowledge(int f) {
        this.kone=f;
        this.ktwo=f;
        this.kthree=f;
        this.kfour=f;
        this.kfive=f;
        this.ksix=f;
        this.kseven=f;
        this.keight=f;
        this.knine=f;
        this.kten=f;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer kone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer ktwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer kthree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer kfour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer kfive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer ksix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer kseven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer keight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer knine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.kTen
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer kten;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kId
     *
     * @return the value of knowledge.kId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKid() {
        return kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kId
     *
     * @param kid the value for knowledge.kId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKid(Integer kid) {
        this.kid = kid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kOne
     *
     * @return the value of knowledge.kOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKone() {
        return kone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kOne
     *
     * @param kone the value for knowledge.kOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKone(Integer kone) {
        this.kone = kone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kTwo
     *
     * @return the value of knowledge.kTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKtwo() {
        return ktwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kTwo
     *
     * @param ktwo the value for knowledge.kTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKtwo(Integer ktwo) {
        this.ktwo = ktwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kThree
     *
     * @return the value of knowledge.kThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKthree() {
        return kthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kThree
     *
     * @param kthree the value for knowledge.kThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKthree(Integer kthree) {
        this.kthree = kthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kFour
     *
     * @return the value of knowledge.kFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKfour() {
        return kfour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kFour
     *
     * @param kfour the value for knowledge.kFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKfour(Integer kfour) {
        this.kfour = kfour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kFive
     *
     * @return the value of knowledge.kFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKfive() {
        return kfive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kFive
     *
     * @param kfive the value for knowledge.kFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKfive(Integer kfive) {
        this.kfive = kfive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kSix
     *
     * @return the value of knowledge.kSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKsix() {
        return ksix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kSix
     *
     * @param ksix the value for knowledge.kSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKsix(Integer ksix) {
        this.ksix = ksix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kSeven
     *
     * @return the value of knowledge.kSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKseven() {
        return kseven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kSeven
     *
     * @param kseven the value for knowledge.kSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKseven(Integer kseven) {
        this.kseven = kseven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kEight
     *
     * @return the value of knowledge.kEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKeight() {
        return keight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kEight
     *
     * @param keight the value for knowledge.kEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKeight(Integer keight) {
        this.keight = keight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kNine
     *
     * @return the value of knowledge.kNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKnine() {
        return knine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kNine
     *
     * @param knine the value for knowledge.kNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKnine(Integer knine) {
        this.knine = knine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.kTen
     *
     * @return the value of knowledge.kTen
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getKten() {
        return kten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.kTen
     *
     * @param kten the value for knowledge.kTen
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setKten(Integer kten) {
        this.kten = kten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.uId
     *
     * @return the value of knowledge.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.uId
     *
     * @param uid the value for knowledge.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}