package cn.Ideal.demo.entity;

import java.util.Date;

public class Mlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlog.lid
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private Integer lid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlog.ltime
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private Date ltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlog.loper
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private String loper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mlog.lcontent
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private String lcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlog.lid
     *
     * @return the value of mlog.lid
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public Integer getLid() {
        return lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlog.lid
     *
     * @param lid the value for mlog.lid
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setLid(Integer lid) {
        this.lid = lid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlog.ltime
     *
     * @return the value of mlog.ltime
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public Date getLtime() {
        return ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlog.ltime
     *
     * @param ltime the value for mlog.ltime
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setLtime(Date ltime) {
        this.ltime = ltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlog.loper
     *
     * @return the value of mlog.loper
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String getLoper() {
        return loper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlog.loper
     *
     * @param loper the value for mlog.loper
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setLoper(String loper) {
        this.loper = loper == null ? null : loper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mlog.lcontent
     *
     * @return the value of mlog.lcontent
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String getLcontent() {
        return lcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mlog.lcontent
     *
     * @param lcontent the value for mlog.lcontent
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setLcontent(String lcontent) {
        this.lcontent = lcontent == null ? null : lcontent.trim();
    }
}