package cn.Ideal.demo.entity;

public class Mrandom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrandom.rid
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private Integer rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrandom.rcontent
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private String rcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrandom.ran1
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private String ran1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrandom.ran2
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private String ran2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mrandom.ran3
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    private String ran3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrandom.rid
     *
     * @return the value of mrandom.rid
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrandom.rid
     *
     * @param rid the value for mrandom.rid
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrandom.rcontent
     *
     * @return the value of mrandom.rcontent
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String getRcontent() {
        return rcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrandom.rcontent
     *
     * @param rcontent the value for mrandom.rcontent
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setRcontent(String rcontent) {
        this.rcontent = rcontent == null ? null : rcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrandom.ran1
     *
     * @return the value of mrandom.ran1
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String getRan1() {
        return ran1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrandom.ran1
     *
     * @param ran1 the value for mrandom.ran1
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setRan1(String ran1) {
        this.ran1 = ran1 == null ? null : ran1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrandom.ran2
     *
     * @return the value of mrandom.ran2
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String getRan2() {
        return ran2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrandom.ran2
     *
     * @param ran2 the value for mrandom.ran2
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setRan2(String ran2) {
        this.ran2 = ran2 == null ? null : ran2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mrandom.ran3
     *
     * @return the value of mrandom.ran3
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String getRan3() {
        return ran3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mrandom.ran3
     *
     * @param ran3 the value for mrandom.ran3
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public void setRan3(String ran3) {
        this.ran3 = ran3 == null ? null : ran3.trim();
    }
}