package cn.Ideal.demo.entity;

import java.math.BigDecimal;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private String pname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pclass
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private String pclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pimg1
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private String pimg1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pimg2
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private String pimg2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pimg3
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private String pimg3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pimg4
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private String pimg4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.change
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private BigDecimal pchange;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pclass
     *
     * @return the value of product.pclass
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String getPclass() {
        return pclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pclass
     *
     * @param pclass the value for product.pclass
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPclass(String pclass) {
        this.pclass = pclass == null ? null : pclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pimg1
     *
     * @return the value of product.pimg1
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String getPimg1() {
        return pimg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pimg1
     *
     * @param pimg1 the value for product.pimg1
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPimg1(String pimg1) {
        this.pimg1 = pimg1 == null ? null : pimg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pimg2
     *
     * @return the value of product.pimg2
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String getPimg2() {
        return pimg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pimg2
     *
     * @param pimg2 the value for product.pimg2
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPimg2(String pimg2) {
        this.pimg2 = pimg2 == null ? null : pimg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pimg3
     *
     * @return the value of product.pimg3
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String getPimg3() {
        return pimg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pimg3
     *
     * @param pimg3 the value for product.pimg3
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPimg3(String pimg3) {
        this.pimg3 = pimg3 == null ? null : pimg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pimg4
     *
     * @return the value of product.pimg4
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String getPimg4() {
        return pimg4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pimg4
     *
     * @param pimg4 the value for product.pimg4
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPimg4(String pimg4) {
        this.pimg4 = pimg4 == null ? null : pimg4.trim();
    }

    public BigDecimal getPchange() {
        return pchange;
    }

    public void setPchange(BigDecimal pchange) {
        this.pchange = pchange;
    }
/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.change
     *
     * @return the value of product.change
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */

}