package cn.Ideal.demo.entity;

public class Quality {
    public Quality(Integer qid, Integer qone, Integer qtwo, Integer qthree, Integer qfour, Integer qfive, Integer qsix, Integer qseven, Integer qeight, Integer qnine, Integer uid) {
        this.qid = qid;
        this.qone = qone;
        this.qtwo = qtwo;
        this.qthree = qthree;
        this.qfour = qfour;
        this.qfive = qfive;
        this.qsix = qsix;
        this.qseven = qseven;
        this.qeight = qeight;
        this.qnine = qnine;
        this.uid = uid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qid;
    public Quality(int f) {
        this.qone=f;
        this.qtwo=f;
        this.qthree=f;
        this.qfour=f;
        this.qfive=f;
        this.qsix=f;
        this.qseven=f;
        this.qeight=f;
        this.qnine=f;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qtwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qthree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qfour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qfive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qsix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qseven;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.qNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer qnine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column quality.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qId
     *
     * @return the value of quality.qId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQid() {
        return qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qId
     *
     * @param qid the value for quality.qId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQid(Integer qid) {
        this.qid = qid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qOne
     *
     * @return the value of quality.qOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQone() {
        return qone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qOne
     *
     * @param qone the value for quality.qOne
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQone(Integer qone) {
        this.qone = qone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qTwo
     *
     * @return the value of quality.qTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQtwo() {
        return qtwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qTwo
     *
     * @param qtwo the value for quality.qTwo
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQtwo(Integer qtwo) {
        this.qtwo = qtwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qThree
     *
     * @return the value of quality.qThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQthree() {
        return qthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qThree
     *
     * @param qthree the value for quality.qThree
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQthree(Integer qthree) {
        this.qthree = qthree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qFour
     *
     * @return the value of quality.qFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQfour() {
        return qfour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qFour
     *
     * @param qfour the value for quality.qFour
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQfour(Integer qfour) {
        this.qfour = qfour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qFive
     *
     * @return the value of quality.qFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQfive() {
        return qfive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qFive
     *
     * @param qfive the value for quality.qFive
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQfive(Integer qfive) {
        this.qfive = qfive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qSix
     *
     * @return the value of quality.qSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQsix() {
        return qsix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qSix
     *
     * @param qsix the value for quality.qSix
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQsix(Integer qsix) {
        this.qsix = qsix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qSeven
     *
     * @return the value of quality.qSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQseven() {
        return qseven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qSeven
     *
     * @param qseven the value for quality.qSeven
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQseven(Integer qseven) {
        this.qseven = qseven;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qEight
     *
     * @return the value of quality.qEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQeight() {
        return qeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qEight
     *
     * @param qeight the value for quality.qEight
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQeight(Integer qeight) {
        this.qeight = qeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.qNine
     *
     * @return the value of quality.qNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getQnine() {
        return qnine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.qNine
     *
     * @param qnine the value for quality.qNine
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setQnine(Integer qnine) {
        this.qnine = qnine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column quality.uId
     *
     * @return the value of quality.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column quality.uId
     *
     * @param uid the value for quality.uId
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}