package cn.Ideal.demo.entity;

import java.util.Date;

public class Replyvip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replyVip.Rid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer rid;

    @Override
    public String toString() {
        return "Replyvip{" +
                "rid=" + rid +
                ", cid=" + cid +
                ", ridrp='" + ridrp + '\'' +
                ", uid=" + uid +
                ", dtime=" + dtime +
                ", father=" + father +
                ", ruid=" + ruid +
                ", ruser=" + ruser +
                ", rn=" + rn +
                ", user=" + user +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replyVip.Cid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replyVip.Ridrp
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private String ridrp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replyVip.uid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replyVip.dtime
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Date dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replyVip.father
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer father;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column replyVip.ruid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    private Integer ruid;
    private User ruser;
    private Integer rn;

    public Integer getRn() {
        return rn;
    }

    public void setRn(Integer rn) {
        this.rn = rn;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    private User user;

    public User getRuser() {
        return ruser;
    }

    public void setRuser(User ruser) {
        this.ruser = ruser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replyVip.Rid
     *
     * @return the value of replyVip.Rid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replyVip.Rid
     *
     * @param rid the value for replyVip.Rid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replyVip.Cid
     *
     * @return the value of replyVip.Cid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replyVip.Cid
     *
     * @param cid the value for replyVip.Cid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replyVip.Ridrp
     *
     * @return the value of replyVip.Ridrp
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String getRidrp() {
        return ridrp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replyVip.Ridrp
     *
     * @param ridrp the value for replyVip.Ridrp
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setRidrp(String ridrp) {
        this.ridrp = ridrp == null ? null : ridrp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replyVip.uid
     *
     * @return the value of replyVip.uid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replyVip.uid
     *
     * @param uid the value for replyVip.uid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replyVip.dtime
     *
     * @return the value of replyVip.dtime
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replyVip.dtime
     *
     * @param dtime the value for replyVip.dtime
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replyVip.father
     *
     * @return the value of replyVip.father
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getFather() {
        return father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replyVip.father
     *
     * @param father the value for replyVip.father
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setFather(Integer father) {
        this.father = father;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column replyVip.ruid
     *
     * @return the value of replyVip.ruid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public Integer getRuid() {
        return ruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column replyVip.ruid
     *
     * @param ruid the value for replyVip.ruid
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public void setRuid(Integer ruid) {
        this.ruid = ruid;
    }
}