package cn.Ideal.demo.entity;

import java.math.BigDecimal;

public class Teaminfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tid
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tname
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private String tname="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tnum
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private Integer tnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tprice
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private BigDecimal tprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.thy
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private String thy="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tleader
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private String tleader="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tphone
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private String tphone="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tcard
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private String tcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.tlogo
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private String tlogo="";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teaminfo.uid
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tid
     *
     * @return the value of teaminfo.tid
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tid
     *
     * @param tid the value for teaminfo.tid
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tname
     *
     * @return the value of teaminfo.tname
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tname
     *
     * @param tname the value for teaminfo.tname
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tnum
     *
     * @return the value of teaminfo.tnum
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public Integer getTnum() {
        return tnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tnum
     *
     * @param tnum the value for teaminfo.tnum
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTnum(Integer tnum) {
        this.tnum = tnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tprice
     *
     * @return the value of teaminfo.tprice
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public BigDecimal getTprice() {
        return tprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tprice
     *
     * @param tprice the value for teaminfo.tprice
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTprice(BigDecimal tprice) {
        this.tprice = tprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.thy
     *
     * @return the value of teaminfo.thy
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String getThy() {
        return thy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.thy
     *
     * @param thy the value for teaminfo.thy
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setThy(String thy) {
        this.thy = thy == null ? null : thy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tleader
     *
     * @return the value of teaminfo.tleader
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String getTleader() {
        return tleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tleader
     *
     * @param tleader the value for teaminfo.tleader
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTleader(String tleader) {
        this.tleader = tleader == null ? null : tleader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tphone
     *
     * @return the value of teaminfo.tphone
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String getTphone() {
        return tphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tphone
     *
     * @param tphone the value for teaminfo.tphone
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTphone(String tphone) {
        this.tphone = tphone == null ? null : tphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tcard
     *
     * @return the value of teaminfo.tcard
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String getTcard() {
        return tcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tcard
     *
     * @param tcard the value for teaminfo.tcard
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTcard(String tcard) {
        this.tcard = tcard == null ? null : tcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.tlogo
     *
     * @return the value of teaminfo.tlogo
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String getTlogo() {
        return tlogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.tlogo
     *
     * @param tlogo the value for teaminfo.tlogo
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setTlogo(String tlogo) {
        this.tlogo = tlogo == null ? null : tlogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teaminfo.uid
     *
     * @return the value of teaminfo.uid
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teaminfo.uid
     *
     * @param uid the value for teaminfo.uid
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}