package cn.Ideal.demo.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uId
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private Integer uid;
private String uimg;

    @Override
    public String toString() {
        return "User{" +
                "uid=" + uid +
                ", uimg='" + uimg + '\'' +
                ", uname='" + uname + '\'' +
                ", upwd='" + upwd + '\'' +
                ", uhy='" + uhy + '\'' +
                ", uproj='" + uproj + '\'' +
                ", province='" + province + '\'' +
                ", city='" + city + '\'' +
                ", utel='" + utel + '\'' +
                '}';
    }

    public String getUimg() {
        return uimg;
    }

    public void setUimg(String uimg) {
        this.uimg = uimg;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uName
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uPwd
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String upwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uHy
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String uhy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uProj
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String uproj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.province
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.city
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uTel
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    private String utel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uId
     *
     * @return the value of user.uId
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uId
     *
     * @param uid the value for user.uId
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uName
     *
     * @return the value of user.uName
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uName
     *
     * @param uname the value for user.uName
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uPwd
     *
     * @return the value of user.uPwd
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uPwd
     *
     * @param upwd the value for user.uPwd
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uHy
     *
     * @return the value of user.uHy
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getUhy() {
        return uhy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uHy
     *
     * @param uhy the value for user.uHy
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setUhy(String uhy) {
        this.uhy = uhy == null ? null : uhy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uProj
     *
     * @return the value of user.uProj
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getUproj() {
        return uproj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uProj
     *
     * @param uproj the value for user.uProj
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setUproj(String uproj) {
        this.uproj = uproj == null ? null : uproj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.province
     *
     * @return the value of user.province
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.province
     *
     * @param province the value for user.province
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.city
     *
     * @return the value of user.city
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.city
     *
     * @param city the value for user.city
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uTel
     *
     * @return the value of user.uTel
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String getUtel() {
        return utel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uTel
     *
     * @param utel the value for user.uTel
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public void setUtel(String utel) {
        this.utel = utel == null ? null : utel.trim();
    }
}