package cn.Ideal.demo.entity;

public class UservipKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userVip.cid
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userVip.uid
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userVip.cid
     *
     * @return the value of userVip.cid
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userVip.cid
     *
     * @param cid the value for userVip.cid
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userVip.uid
     *
     * @return the value of userVip.uid
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userVip.uid
     *
     * @param uid the value for userVip.uid
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}