package cn.Ideal.demo.entity;

import java.math.BigDecimal;

public class Warehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.wid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer wid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.uid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.wprice
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private BigDecimal wprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.wnum
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    private Integer wnum;
    private Product product;

    @Override
    public String toString() {
        return "Warehouse{" +
                "wid=" + wid +
                ", pid=" + pid +
                ", uid=" + uid +
                ", wprice=" + wprice +
                ", wnum=" + wnum +
                ", product=" + product +
                '}';
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.wid
     *
     * @return the value of warehouse.wid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.wid
     *
     * @param wid the value for warehouse.wid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setWid(Integer wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.pid
     *
     * @return the value of warehouse.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.pid
     *
     * @param pid the value for warehouse.pid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.uid
     *
     * @return the value of warehouse.uid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.uid
     *
     * @param uid the value for warehouse.uid
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.wprice
     *
     * @return the value of warehouse.wprice
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public BigDecimal getWprice() {
        return wprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.wprice
     *
     * @param wprice the value for warehouse.wprice
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setWprice(BigDecimal wprice) {
        this.wprice = wprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.wnum
     *
     * @return the value of warehouse.wnum
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public Integer getWnum() {
        return wnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.wnum
     *
     * @param wnum the value for warehouse.wnum
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public void setWnum(Integer wnum) {
        this.wnum = wnum;
    }
}