package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Ability;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
public interface AbilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    @Delete({
        "delete from ability",
        "where aId = #{aid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    @Insert({
        "insert into ability (aId, aOne, ",
        "aTwo, aThree, aFour, ",
        "aFive, aSix, aSeven, ",
        "aEight, aNine, aTen, ",
        "aEleven, uId)",
        "values (#{aid,jdbcType=INTEGER}, #{aone,jdbcType=INTEGER}, ",
        "#{atwo,jdbcType=INTEGER}, #{athree,jdbcType=INTEGER}, #{afour,jdbcType=INTEGER}, ",
        "#{afive,jdbcType=INTEGER}, #{asix,jdbcType=INTEGER}, #{aseven,jdbcType=INTEGER}, ",
        "#{aeight,jdbcType=INTEGER}, #{anine,jdbcType=INTEGER}, #{aten,jdbcType=INTEGER}, ",
        "#{aeleven,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER})"
    })
    int insert(Ability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    @InsertProvider(type=AbilitySqlProvider.class, method="insertSelective")
    int insertSelective(Ability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    @Select({
        "select",
        "aId, aOne, aTwo, aThree, aFour, aFive, aSix, aSeven, aEight, aNine, aTen, aEleven, ",
        "uId",
        "from ability",
        "where aId = #{aid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="aId", property="aid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="aOne", property="aone", jdbcType=JdbcType.INTEGER),
        @Result(column="aTwo", property="atwo", jdbcType=JdbcType.INTEGER),
        @Result(column="aThree", property="athree", jdbcType=JdbcType.INTEGER),
        @Result(column="aFour", property="afour", jdbcType=JdbcType.INTEGER),
        @Result(column="aFive", property="afive", jdbcType=JdbcType.INTEGER),
        @Result(column="aSix", property="asix", jdbcType=JdbcType.INTEGER),
        @Result(column="aSeven", property="aseven", jdbcType=JdbcType.INTEGER),
        @Result(column="aEight", property="aeight", jdbcType=JdbcType.INTEGER),
        @Result(column="aNine", property="anine", jdbcType=JdbcType.INTEGER),
        @Result(column="aTen", property="aten", jdbcType=JdbcType.INTEGER),
        @Result(column="aEleven", property="aeleven", jdbcType=JdbcType.INTEGER),
        @Result(column="uId", property="uid", jdbcType=JdbcType.INTEGER)
    })
    Ability selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    @UpdateProvider(type=AbilitySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Ability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    @Update({
        "update ability",
        "set aOne = #{aone,jdbcType=INTEGER},",
          "aTwo = #{atwo,jdbcType=INTEGER},",
          "aThree = #{athree,jdbcType=INTEGER},",
          "aFour = #{afour,jdbcType=INTEGER},",
          "aFive = #{afive,jdbcType=INTEGER},",
          "aSix = #{asix,jdbcType=INTEGER},",
          "aSeven = #{aseven,jdbcType=INTEGER},",
          "aEight = #{aeight,jdbcType=INTEGER},",
          "aNine = #{anine,jdbcType=INTEGER},",
          "aTen = #{aten,jdbcType=INTEGER},",
          "aEleven = #{aeleven,jdbcType=INTEGER},",
          "uId = #{uid,jdbcType=INTEGER}",
        "where aId = #{aid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ability record);


    @Update({
            "update ability",
            "set aOne = 10,",
            "aTwo = 10,",
            "aThree = 10,",
            "aFour = 10,",
            "aFive = 10,",
            "aSix = 10,",
            "aSeven = 10,",
            "aEight = 10,",
            "aNine = 10,",
            "aTen = 10,",
            "aEleven = 10,",
            "uId = #{uid,jdbcType=INTEGER}",
            "where uId = #{uid,jdbcType=INTEGER}"
    })
    int initHaveAbility(Integer uid);

    @Insert({
            "insert into ability (aId, aOne, ",
            "aTwo, aThree, aFour, ",
            "aFive, aSix, aSeven, ",
            "aEight, aNine, aTen, ",
            "aEleven, uId)",
            "values (#{aid,jdbcType=INTEGER}, #{aone,jdbcType=INTEGER}, ",
            "#{atwo,jdbcType=INTEGER}, #{athree,jdbcType=INTEGER}, #{afour,jdbcType=INTEGER}, ",
            "#{afive,jdbcType=INTEGER}, #{asix,jdbcType=INTEGER}, #{aseven,jdbcType=INTEGER}, ",
            "#{aeight,jdbcType=INTEGER}, #{anine,jdbcType=INTEGER}, #{aten,jdbcType=INTEGER}, ",
            "#{aeleven,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER})"
    })
    int initNotHaveAbility(Ability record);


    @Select({
            "select",
            "aId, aOne, aTwo, aThree, aFour, aFive, aSix, aSeven, aEight, aNine, aTen, aEleven, ",
            "uId",
            "from ability",
            "where uid = #{uid,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="aId", property="aid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="aOne", property="aone", jdbcType=JdbcType.INTEGER),
            @Result(column="aTwo", property="atwo", jdbcType=JdbcType.INTEGER),
            @Result(column="aThree", property="athree", jdbcType=JdbcType.INTEGER),
            @Result(column="aFour", property="afour", jdbcType=JdbcType.INTEGER),
            @Result(column="aFive", property="afive", jdbcType=JdbcType.INTEGER),
            @Result(column="aSix", property="asix", jdbcType=JdbcType.INTEGER),
            @Result(column="aSeven", property="aseven", jdbcType=JdbcType.INTEGER),
            @Result(column="aEight", property="aeight", jdbcType=JdbcType.INTEGER),
            @Result(column="aNine", property="anine", jdbcType=JdbcType.INTEGER),
            @Result(column="aTen", property="aten", jdbcType=JdbcType.INTEGER),
            @Result(column="aEleven", property="aeleven", jdbcType=JdbcType.INTEGER),
            @Result(column="uId", property="uid", jdbcType=JdbcType.INTEGER)
    })
    Ability selectByUid(Integer uid);
}