package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Ability;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class AbilitySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public String insertSelective(Ability record) {
        BEGIN();
        INSERT_INTO("ability");
        
        if (record.getAid() != null) {
            VALUES("aId", "#{aid,jdbcType=INTEGER}");
        }
        
        if (record.getAone() != null) {
            VALUES("aOne", "#{aone,jdbcType=INTEGER}");
        }
        
        if (record.getAtwo() != null) {
            VALUES("aTwo", "#{atwo,jdbcType=INTEGER}");
        }
        
        if (record.getAthree() != null) {
            VALUES("aThree", "#{athree,jdbcType=INTEGER}");
        }
        
        if (record.getAfour() != null) {
            VALUES("aFour", "#{afour,jdbcType=INTEGER}");
        }
        
        if (record.getAfive() != null) {
            VALUES("aFive", "#{afive,jdbcType=INTEGER}");
        }
        
        if (record.getAsix() != null) {
            VALUES("aSix", "#{asix,jdbcType=INTEGER}");
        }
        
        if (record.getAseven() != null) {
            VALUES("aSeven", "#{aseven,jdbcType=INTEGER}");
        }
        
        if (record.getAeight() != null) {
            VALUES("aEight", "#{aeight,jdbcType=INTEGER}");
        }
        
        if (record.getAnine() != null) {
            VALUES("aNine", "#{anine,jdbcType=INTEGER}");
        }
        
        if (record.getAten() != null) {
            VALUES("aTen", "#{aten,jdbcType=INTEGER}");
        }
        
        if (record.getAeleven() != null) {
            VALUES("aEleven", "#{aeleven,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uId", "#{uid,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ability
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Ability record) {
        BEGIN();
        UPDATE("ability");
        
        if (record.getAone() != null) {
            SET("aOne = #{aone,jdbcType=INTEGER}");
        }
        
        if (record.getAtwo() != null) {
            SET("aTwo = #{atwo,jdbcType=INTEGER}");
        }
        
        if (record.getAthree() != null) {
            SET("aThree = #{athree,jdbcType=INTEGER}");
        }
        
        if (record.getAfour() != null) {
            SET("aFour = #{afour,jdbcType=INTEGER}");
        }
        
        if (record.getAfive() != null) {
            SET("aFive = #{afive,jdbcType=INTEGER}");
        }
        
        if (record.getAsix() != null) {
            SET("aSix = #{asix,jdbcType=INTEGER}");
        }
        
        if (record.getAseven() != null) {
            SET("aSeven = #{aseven,jdbcType=INTEGER}");
        }
        
        if (record.getAeight() != null) {
            SET("aEight = #{aeight,jdbcType=INTEGER}");
        }
        
        if (record.getAnine() != null) {
            SET("aNine = #{anine,jdbcType=INTEGER}");
        }
        
        if (record.getAten() != null) {
            SET("aTen = #{aten,jdbcType=INTEGER}");
        }
        
        if (record.getAeleven() != null) {
            SET("aEleven = #{aeleven,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            SET("uId = #{uid,jdbcType=INTEGER}");
        }
        
        WHERE("aId = #{aid,jdbcType=INTEGER}");
        
        return SQL();
    }
}