package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Commentvip;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class CommentvipSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String insertSelective(Commentvip record) {
        BEGIN();
        INSERT_INTO("commentVip");
        
        if (record.getCid() != null) {
            VALUES("Cid", "#{cid,jdbcType=INTEGER}");
        }
        
        if (record.getCimg() != null) {
            VALUES("cimg", "#{cimg,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getTips() != null) {
            VALUES("tips", "#{tips,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            VALUES("Ctime", "#{ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCount() != null) {
            VALUES("count", "#{count,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Commentvip record) {
        BEGIN();
        UPDATE("commentVip");
        
        if (record.getCimg() != null) {
            SET("cimg = #{cimg,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getTips() != null) {
            SET("tips = #{tips,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            SET("Ctime = #{ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getCount() != null) {
            SET("count = #{count,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        WHERE("Cid = #{cid,jdbcType=INTEGER}");
        
        return SQL();
    }
}