package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Comment;
import cn.Ideal.demo.entity.Commentvip;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface CommentvipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    @Delete({
        "delete from commentVip",
        "where Cid = #{cid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    @Insert({
        "insert into commentVip (Cid, cimg, ",
        "title, content, ",
        "tips, Ctime, count, ",
        "uid)",
        "values (#{cid,jdbcType=INTEGER}, #{cimg,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{tips,jdbcType=VARCHAR}, #{ctime,jdbcType=TIMESTAMP}, #{count,jdbcType=INTEGER}, ",
        "#{uid,jdbcType=INTEGER})"
    })
    int insert(Commentvip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    @InsertProvider(type=CommentvipSqlProvider.class, method="insertSelective")
    int insertSelective(Commentvip record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    @UpdateProvider(type=CommentvipSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Commentvip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    @Update({
        "update commentVip",
        "set cimg = #{cimg,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "tips = #{tips,jdbcType=VARCHAR},",
          "Ctime = #{ctime,jdbcType=TIMESTAMP},",
          "count = #{count,jdbcType=INTEGER},",
          "uid = #{uid,jdbcType=INTEGER}",
        "where Cid = #{cid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Commentvip record);


    @Select({
            "select",
            "Cid, cimg, title, content, tips, Ctime, count, uid",
            "from commentVip",
            "where title like CONCAT('%',#{keyWords,jdbcType=VARCHAR},'%') or content like CONCAT('%',#{keyWords,jdbcType=VARCHAR},'%')",
            " or tips like CONCAT('%',#{keyWords,jdbcType=VARCHAR},'%')"
    })
    @Results({
            @Result(column="Cid", property="cid", jdbcType=JdbcType.INTEGER),
            @Result(column="cimg", property="cimg", jdbcType=JdbcType.VARCHAR),
            @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
            @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
            @Result(column="tips", property="tips", jdbcType=JdbcType.VARCHAR),
            @Result(column="Ctime", property="ctime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="count", property="count", jdbcType=JdbcType.INTEGER),
            @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER)
    })
    List<Commentvip> selectKeywords(String keywords);


    @Select({
            "select",
            "Cid, cimg, title, content, tips, Ctime, count, uid",
            "from commentVip",
            "where Cid = #{cid,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="Cid", property="cid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="cimg", property="cimg", jdbcType=JdbcType.VARCHAR),
            @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
            @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
            @Result(column="tips", property="tips", jdbcType=JdbcType.VARCHAR),
            @Result(column="Ctime", property="ctime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="count", property="count", jdbcType=JdbcType.INTEGER),
            @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
            @Result(column ="uid",property = "user",one = @One(select = "cn.Ideal.demo.dao.UserMapper.selectByPrimaryKey"))
    })
    Commentvip selectByPrimaryKey(Integer cid);
}