package cn.Ideal.demo.dao;



import cn.Ideal.demo.entity.Comment;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class CommentSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String insertSelective(Comment record) {
        BEGIN();
        INSERT_INTO("comment");
        
        if (record.getCid() != null) {
            VALUES("Cid", "#{cid,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            VALUES("content", "#{content,jdbcType=VARCHAR}");
        }
        
        if (record.getTips() != null) {
            VALUES("tips", "#{tips,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            VALUES("Ctime", "#{ctime,jdbcType=VARCHAR}");
        }
        
        if (record.getCount() != null) {
            VALUES("count", "#{count,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Comment record) {
        BEGIN();
        UPDATE("comment");
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getContent() != null) {
            SET("content = #{content,jdbcType=VARCHAR}");
        }
        
        if (record.getTips() != null) {
            SET("tips = #{tips,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            SET("Ctime = #{ctime,jdbcType=VARCHAR}");
        }
        
        if (record.getCount() != null) {
            SET("count = #{count,jdbcType=INTEGER}");
        }
        
        WHERE("Cid = #{cid,jdbcType=INTEGER}");
        
        return SQL();
    }
}