package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Info;


import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class InfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String insertSelective(Info record) {
        BEGIN();
        INSERT_INTO("info");
        
        if (record.getIid() != null) {
            VALUES("iid", "#{iid,jdbcType=INTEGER}");
        }
        
        if (record.getIcontent() != null) {
            VALUES("icontent", "#{icontent,jdbcType=VARCHAR}");
        }
        
        if (record.getPid() != null) {
            VALUES("pid", "#{pid,jdbcType=INTEGER}");
        }
        
        if (record.getUpdown() != null) {
            VALUES("updown", "#{updown,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Info record) {
        BEGIN();
        UPDATE("info");
        
        if (record.getIcontent() != null) {
            SET("icontent = #{icontent,jdbcType=VARCHAR}");
        }
        
        if (record.getPid() != null) {
            SET("pid = #{pid,jdbcType=INTEGER}");
        }
        
        if (record.getUpdown() != null) {
            SET("updown = #{updown,jdbcType=INTEGER}");
        }
        
        WHERE("iid = #{iid,jdbcType=INTEGER}");
        
        return SQL();
    }
}