package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Info;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
public interface InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Delete({
        "delete from info",
        "where iid = #{iid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Insert({
        "insert into info (iid, icontent, ",
        "pid, updown)",
        "values (#{iid,jdbcType=INTEGER}, #{icontent,jdbcType=VARCHAR}, ",
        "#{pid,jdbcType=INTEGER}, #{updown,jdbcType=INTEGER})"
    })
    int insert(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @InsertProvider(type=InfoSqlProvider.class, method="insertSelective")
    int insertSelective(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Select({
        "select",
        "iid, icontent, pid, updown",
        "from info",
        "where iid = #{iid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="iid", property="iid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="icontent", property="icontent", jdbcType=JdbcType.VARCHAR),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
        @Result(column="updown", property="updown", jdbcType=JdbcType.INTEGER)
    })
    Info selectByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @UpdateProvider(type=InfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Update({
        "update info",
        "set icontent = #{icontent,jdbcType=VARCHAR},",
          "pid = #{pid,jdbcType=INTEGER},",
          "updown = #{updown,jdbcType=INTEGER}",
        "where iid = #{iid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Info record);


    @Select({
            "select",
            "iid, icontent, pid, updown",
            "from info",
            "where pid = #{pid,jdbcType=INTEGER} and updown = #{updown,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="iid", property="iid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="icontent", property="icontent", jdbcType=JdbcType.VARCHAR),
            @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
            @Result(column="updown", property="updown", jdbcType=JdbcType.INTEGER)
    })
    Info selectInfo(@Param("pid")Integer pid ,@Param("updown")Integer updown);
}