package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Knowledge;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class KnowledgeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public String insertSelective(Knowledge record) {
        BEGIN();
        INSERT_INTO("knowledge");
        
        if (record.getKid() != null) {
            VALUES("kId", "#{kid,jdbcType=INTEGER}");
        }
        
        if (record.getKone() != null) {
            VALUES("kOne", "#{kone,jdbcType=INTEGER}");
        }
        
        if (record.getKtwo() != null) {
            VALUES("kTwo", "#{ktwo,jdbcType=INTEGER}");
        }
        
        if (record.getKthree() != null) {
            VALUES("kThree", "#{kthree,jdbcType=INTEGER}");
        }
        
        if (record.getKfour() != null) {
            VALUES("kFour", "#{kfour,jdbcType=INTEGER}");
        }
        
        if (record.getKfive() != null) {
            VALUES("kFive", "#{kfive,jdbcType=INTEGER}");
        }
        
        if (record.getKsix() != null) {
            VALUES("kSix", "#{ksix,jdbcType=INTEGER}");
        }
        
        if (record.getKseven() != null) {
            VALUES("kSeven", "#{kseven,jdbcType=INTEGER}");
        }
        
        if (record.getKeight() != null) {
            VALUES("kEight", "#{keight,jdbcType=INTEGER}");
        }
        
        if (record.getKnine() != null) {
            VALUES("kNine", "#{knine,jdbcType=INTEGER}");
        }
        
        if (record.getKten() != null) {
            VALUES("kTen", "#{kten,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uId", "#{uid,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledge
     *
     * @mbggenerated Wed May 22 18:37:34 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Knowledge record) {
        BEGIN();
        UPDATE("knowledge");
        
        if (record.getKone() != null) {
            SET("kOne = #{kone,jdbcType=INTEGER}");
        }
        
        if (record.getKtwo() != null) {
            SET("kTwo = #{ktwo,jdbcType=INTEGER}");
        }
        
        if (record.getKthree() != null) {
            SET("kThree = #{kthree,jdbcType=INTEGER}");
        }
        
        if (record.getKfour() != null) {
            SET("kFour = #{kfour,jdbcType=INTEGER}");
        }
        
        if (record.getKfive() != null) {
            SET("kFive = #{kfive,jdbcType=INTEGER}");
        }
        
        if (record.getKsix() != null) {
            SET("kSix = #{ksix,jdbcType=INTEGER}");
        }
        
        if (record.getKseven() != null) {
            SET("kSeven = #{kseven,jdbcType=INTEGER}");
        }
        
        if (record.getKeight() != null) {
            SET("kEight = #{keight,jdbcType=INTEGER}");
        }
        
        if (record.getKnine() != null) {
            SET("kNine = #{knine,jdbcType=INTEGER}");
        }
        
        if (record.getKten() != null) {
            SET("kTen = #{kten,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            SET("uId = #{uid,jdbcType=INTEGER}");
        }
        
        WHERE("kId = #{kid,jdbcType=INTEGER}");
        
        return SQL();
    }
}