package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Mlog;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class MlogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlog
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String insertSelective(Mlog record) {
        BEGIN();
        INSERT_INTO("mlog");
        
        if (record.getLid() != null) {
            VALUES("lid", "#{lid,jdbcType=INTEGER}");
        }
        
        if (record.getLtime() != null) {
            VALUES("ltime", "#{ltime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getLoper() != null) {
            VALUES("loper", "#{loper,jdbcType=VARCHAR}");
        }
        
        if (record.getLcontent() != null) {
            VALUES("lcontent", "#{lcontent,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mlog
     *
     * @mbggenerated Fri Apr 26 20:07:20 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Mlog record) {
        BEGIN();
        UPDATE("mlog");
        
        if (record.getLtime() != null) {
            SET("ltime = #{ltime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getLoper() != null) {
            SET("loper = #{loper,jdbcType=VARCHAR}");
        }
        
        if (record.getLcontent() != null) {
            SET("lcontent = #{lcontent,jdbcType=VARCHAR}");
        }
        
        WHERE("lid = #{lid,jdbcType=INTEGER}");
        
        return SQL();
    }
}