package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Product;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Delete({
        "delete from product",
        "where pid = #{pid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Insert({
        "insert into product (pid, pname, ",
        "price, pclass, pimg1, ",
        "pimg2, pimg3, pimg4, ",
        "change)",
        "values (#{pid,jdbcType=INTEGER}, #{pname,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{pclass,jdbcType=VARCHAR}, #{pimg1,jdbcType=VARCHAR}, ",
        "#{pimg2,jdbcType=VARCHAR}, #{pimg3,jdbcType=VARCHAR}, #{pimg4,jdbcType=VARCHAR}, ",
        "#{change,jdbcType=DECIMAL})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @InsertProvider(type=ProductSqlProvider.class, method="insertSelective")
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Select({
        "select",
        "pid, pname, price, pclass, pimg1, pimg2, pimg3, pimg4",
        "from product",
        "where pid = #{pid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pname", property="pname", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
        @Result(column="pclass", property="pclass", jdbcType=JdbcType.VARCHAR),
        @Result(column="pimg1", property="pimg1", jdbcType=JdbcType.VARCHAR),
        @Result(column="pimg2", property="pimg2", jdbcType=JdbcType.VARCHAR),
        @Result(column="pimg3", property="pimg3", jdbcType=JdbcType.VARCHAR),
        @Result(column="pimg4", property="pimg4", jdbcType=JdbcType.VARCHAR),
        @Result(column="change", property="change", jdbcType=JdbcType.DECIMAL)
    })
    Product selectByPrimaryKey(Integer pid);
    @Select({
            "select",
            "pid, pname, price, pclass",
            "from product"
    })
    @Results({
            @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="pname", property="pname", jdbcType=JdbcType.VARCHAR),
            @Result(column="price", property="price", jdbcType=JdbcType.DECIMAL),
            @Result(column="pclass", property="pclass", jdbcType=JdbcType.VARCHAR)
    })
    List<Product> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @UpdateProvider(type=ProductSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Update({
        "update product",
        "set pname = #{pname,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "pclass = #{pclass,jdbcType=VARCHAR},",
          "pimg1 = #{pimg1,jdbcType=VARCHAR},",
          "pimg2 = #{pimg2,jdbcType=VARCHAR},",
          "pimg3 = #{pimg3,jdbcType=VARCHAR},",
          "pimg4 = #{pimg4,jdbcType=VARCHAR},",
          "pchange = #{pchange,jdbcType=DECIMAL}",
        "where pid = #{pid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
    @Update({
            "update product",
            "set ",
            "pchange = #{pchange,jdbcType=DECIMAL}",
            "where pid = #{pid,jdbcType=INTEGER}"
    })
    int updatePchange(@Param("pid") Integer pid,@Param("pchange") float pchange);


    @Update({
            "update product",
            "set ",
            "price = price+ pchange,pchange=0"
    })
    int updatePriceAndPchange();

    @Update({
            "update product",
            "set ",
            "price = pid*10+30"
    })
    int productInit();
}