package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Replyvip;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class ReplyvipSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replyVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String insertSelective(Replyvip record) {
        BEGIN();
        INSERT_INTO("replyVip");
        
        if (record.getRid() != null) {
            VALUES("Rid", "#{rid,jdbcType=INTEGER}");
        }
        
        if (record.getCid() != null) {
            VALUES("Cid", "#{cid,jdbcType=INTEGER}");
        }
        
        if (record.getRidrp() != null) {
            VALUES("Ridrp", "#{ridrp,jdbcType=VARCHAR}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getDtime() != null) {
            VALUES("dtime", "#{dtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFather() != null) {
            VALUES("father", "#{father,jdbcType=INTEGER}");
        }
        
        if (record.getRuid() != null) {
            VALUES("ruid", "#{ruid,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table replyVip
     *
     * @mbggenerated Sat Apr 20 19:02:01 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Replyvip record) {
        BEGIN();
        UPDATE("replyVip");
        
        if (record.getCid() != null) {
            SET("Cid = #{cid,jdbcType=INTEGER}");
        }
        
        if (record.getRidrp() != null) {
            SET("Ridrp = #{ridrp,jdbcType=VARCHAR}");
        }
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        if (record.getDtime() != null) {
            SET("dtime = #{dtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFather() != null) {
            SET("father = #{father,jdbcType=INTEGER}");
        }
        
        if (record.getRuid() != null) {
            SET("ruid = #{ruid,jdbcType=INTEGER}");
        }
        
        WHERE("Rid = #{rid,jdbcType=INTEGER}");
        
        return SQL();
    }
}