package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Reply;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class ReplySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated Sat Apr 13 12:40:47 GMT+08:00 2019
     */
    public String insertSelective(Reply record) {
        BEGIN();
        INSERT_INTO("reply");
        
        if (record.getRid() != null) {
            VALUES("Rid", "#{rid,jdbcType=INTEGER}");
        }
        
        if (record.getCid() != null) {
            VALUES("Cid", "#{cid,jdbcType=INTEGER}");
        }
        
        if (record.getRidrp() != null) {
            VALUES("Ridrp", "#{ridrp,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getDtime() != null) {
            VALUES("dtime", "#{dtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFather() != null) {
            VALUES("father", "#{father,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply
     *
     * @mbggenerated Sat Apr 13 12:40:47 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Reply record) {
        BEGIN();
        UPDATE("reply");
        
        if (record.getCid() != null) {
            SET("Cid = #{cid,jdbcType=INTEGER}");
        }
        
        if (record.getRidrp() != null) {
            SET("Ridrp = #{ridrp,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        if (record.getDtime() != null) {
            SET("dtime = #{dtime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getFather() != null) {
            SET("father = #{father,jdbcType=INTEGER}");
        }
        
        WHERE("Rid = #{rid,jdbcType=INTEGER}");
        
        return SQL();
    }
}