package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Teaminfo;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class TeaminfoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String insertSelective(Teaminfo record) {
        BEGIN();
        INSERT_INTO("teaminfo");
        
        if (record.getTid() != null) {
            VALUES("tid", "#{tid,jdbcType=INTEGER}");
        }
        
        if (record.getTname() != null) {
            VALUES("tname", "#{tname,jdbcType=VARCHAR}");
        }
        
        if (record.getTnum() != null) {
            VALUES("tnum", "#{tnum,jdbcType=INTEGER}");
        }
        
        if (record.getTprice() != null) {
            VALUES("tprice", "#{tprice,jdbcType=DECIMAL}");
        }
        
        if (record.getThy() != null) {
            VALUES("thy", "#{thy,jdbcType=VARCHAR}");
        }
        
        if (record.getTleader() != null) {
            VALUES("tleader", "#{tleader,jdbcType=VARCHAR}");
        }
        
        if (record.getTphone() != null) {
            VALUES("tphone", "#{tphone,jdbcType=VARCHAR}");
        }
        
        if (record.getTcard() != null) {
            VALUES("tcard", "#{tcard,jdbcType=VARCHAR}");
        }
        
        if (record.getTlogo() != null) {
            VALUES("tlogo", "#{tlogo,jdbcType=VARCHAR}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teaminfo
     *
     * @mbggenerated Wed Apr 24 23:35:16 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Teaminfo record) {
        BEGIN();
        UPDATE("teaminfo");
        
        if (record.getTname() != null) {
            SET("tname = #{tname,jdbcType=VARCHAR}");
        }
        
        if (record.getTnum() != null) {
            SET("tnum = #{tnum,jdbcType=INTEGER}");
        }
        
        if (record.getTprice() != null) {
            SET("tprice = #{tprice,jdbcType=DECIMAL}");
        }
        
        if (record.getThy() != null) {
            SET("thy = #{thy,jdbcType=VARCHAR}");
        }
        
        if (record.getTleader() != null) {
            SET("tleader = #{tleader,jdbcType=VARCHAR}");
        }
        
        if (record.getTphone() != null) {
            SET("tphone = #{tphone,jdbcType=VARCHAR}");
        }
        
        if (record.getTcard() != null) {
            SET("tcard = #{tcard,jdbcType=VARCHAR}");
        }
        
        if (record.getTlogo() != null) {
            SET("tlogo = #{tlogo,jdbcType=VARCHAR}");
        }
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        WHERE("tid = #{tid,jdbcType=INTEGER}");
        
        return SQL();
    }
}