package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.UservipKey;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.springframework.stereotype.Component;

@Component
public interface UservipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVip
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    @Delete({
        "delete from userVip",
        "where cid = #{cid,jdbcType=INTEGER}",
          "and uid = #{uid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UservipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVip
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    @Insert({
        "insert into userVip (cid, uid)",
        "values (#{cid,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER})"
    })
    int insert(UservipKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVip
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    @InsertProvider(type=UservipSqlProvider.class, method="insertSelective")
    int insertSelective(UservipKey record);
}