package cn.Ideal.demo.dao;



import cn.Ideal.demo.entity.User;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String insertSelective(User record) {
        BEGIN();
        INSERT_INTO("user");
        
        if (record.getUid() != null) {
            VALUES("uId", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getUname() != null) {
            VALUES("uName", "#{uname,jdbcType=VARCHAR}");
        }
        
        if (record.getUpwd() != null) {
            VALUES("uPwd", "#{upwd,jdbcType=VARCHAR}");
        }
        
        if (record.getUhy() != null) {
            VALUES("uHy", "#{uhy,jdbcType=VARCHAR}");
        }
        
        if (record.getUproj() != null) {
            VALUES("uProj", "#{uproj,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            VALUES("province", "#{province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            VALUES("city", "#{city,jdbcType=VARCHAR}");
        }
        
        if (record.getUtel() != null) {
            VALUES("uTel", "#{utel,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(User record) {
        BEGIN();
        UPDATE("user");
        
        if (record.getUname() != null) {
            SET("uName = #{uname,jdbcType=VARCHAR}");
        }
        
        if (record.getUpwd() != null) {
            SET("uPwd = #{upwd,jdbcType=VARCHAR}");
        }
        
        if (record.getUhy() != null) {
            SET("uHy = #{uhy,jdbcType=VARCHAR}");
        }
        
        if (record.getUproj() != null) {
            SET("uProj = #{uproj,jdbcType=VARCHAR}");
        }
        
        if (record.getProvince() != null) {
            SET("province = #{province,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            SET("city = #{city,jdbcType=VARCHAR}");
        }
        
        if (record.getUtel() != null) {
            SET("uTel = #{utel,jdbcType=VARCHAR}");
        }
        
        WHERE("uId = #{uid,jdbcType=INTEGER}");
        
        return SQL();
    }
}