package cn.Ideal.demo.dao;


import cn.Ideal.demo.entity.User;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

@Component
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    @Delete({
        "delete from user",
        "where uId = #{uid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    @Insert({
        "insert into user (uId, uName, ",
        "uPwd, uHy, uProj, ",
        "province, city, ",
        "uTel,uimg)",
        "values (#{uid,jdbcType=INTEGER}, #{uname,jdbcType=VARCHAR}, ",
        "#{upwd,jdbcType=VARCHAR}, #{uhy,jdbcType=VARCHAR}, #{uproj,jdbcType=VARCHAR}, ",
        "#{province,jdbcType=VARCHAR}, #{city,jdbcType=VARCHAR}, ",
        "#{utel,jdbcType=VARCHAR},#{uimg,jdbcType=VARCHAR})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    @InsertProvider(type=UserSqlProvider.class, method="insertSelective")
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    @Select({
        "select",
        "uId, uName, uPwd, uHy, uProj, province, city, uTel,uimg,ubalance",
        "from user",
        "where uId = #{uid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="uId", property="uid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="uName", property="uname", jdbcType=JdbcType.VARCHAR),
        @Result(column="uPwd", property="upwd", jdbcType=JdbcType.VARCHAR),
        @Result(column="uHy", property="uhy", jdbcType=JdbcType.VARCHAR),
        @Result(column="uProj", property="uproj", jdbcType=JdbcType.VARCHAR),
        @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
        @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
        @Result(column="uTel", property="utel", jdbcType=JdbcType.VARCHAR),
        @Result(column="uimg", property="uimg", jdbcType=JdbcType.VARCHAR),
        @Result(column="ubalance", property="ubalance", jdbcType=JdbcType.DECIMAL)
    })
    User selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Apr 09 19:52:55 GMT+08:00 2019
     */
    @Update({
        "update user",
        "set uName = #{uname,jdbcType=VARCHAR},",
          "uPwd = #{upwd,jdbcType=VARCHAR},",
          "uHy = #{uhy,jdbcType=VARCHAR},",
          "uProj = #{uproj,jdbcType=VARCHAR},",
          "province = #{province,jdbcType=VARCHAR},",
          "city = #{city,jdbcType=VARCHAR},",
          "uTel = #{utel,jdbcType=VARCHAR}",
        "where uId = #{uid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);

    @Select({
            "select",
            "uId, uName, uPwd, uHy, uProj, province, city, uTel",
            "from user",
            "where uName = #{uName,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="uId", property="uid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="uName", property="uname", jdbcType=JdbcType.VARCHAR),
            @Result(column="uPwd", property="upwd", jdbcType=JdbcType.VARCHAR),
            @Result(column="uHy", property="uhy", jdbcType=JdbcType.VARCHAR),
            @Result(column="uProj", property="uproj", jdbcType=JdbcType.VARCHAR),
            @Result(column="province", property="province", jdbcType=JdbcType.VARCHAR),
            @Result(column="city", property="city", jdbcType=JdbcType.VARCHAR),
            @Result(column="uTel", property="utel", jdbcType=JdbcType.VARCHAR)
    })
    User selectByUsername(String uName);
    @Update({
            "update user",
            "set ubalance =ubalance-#{price,jdbcType=INTEGER}",
            "where uId = #{uid,jdbcType=INTEGER}"
    })
    int updatePayVipComment(@Param("price")Integer price,@Param("uid")Integer uid);
}