package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.UservipKey;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface UservipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVip
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    @Delete({
        "delete from userVip",
        "where cid = #{cid,jdbcType=INTEGER}",
          "and uid = #{uid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(UservipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVip
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    @Insert({
        "insert into userVip (cid, uid)",
        "values (#{cid,jdbcType=INTEGER}, #{uid,jdbcType=INTEGER})"
    })
    int insert(@Param("uid")Integer uid,@Param("cid")Integer cid);
    @Select({
            "select",
            "count(*) as uservipKey",
            "from userVip",
            "where uid=#{uvip,jdbcType=INTEGER} and cid=#{Cid,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="uservipKey", property="uservipKey", jdbcType=JdbcType.INTEGER)
    })
    Integer selectUserVip(@Param("uvip")Integer uvip,@Param("Cid")Integer Cid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVip
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    @InsertProvider(type=UservipSqlProvider.class, method="insertSelective")
    int insertSelective(UservipKey record);
}