package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.UservipKey;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class UservipSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userVip
     *
     * @mbggenerated Sat Apr 20 19:49:55 GMT+08:00 2019
     */
    public String insertSelective(UservipKey record) {
        BEGIN();
        INSERT_INTO("userVip");
        
        if (record.getCid() != null) {
            VALUES("cid", "#{cid,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        return SQL();
    }
}