package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Warehouse;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface WarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Delete({
        "delete from warehouse",
        "where wid = #{wid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer wid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Insert({
        "insert into warehouse (wid, pid, ",
        "uid, wprice, wnum)",
        "values (#{wid,jdbcType=INTEGER}, #{pid,jdbcType=INTEGER}, ",
        "#{uid,jdbcType=INTEGER}, #{wprice,jdbcType=DECIMAL}, #{wnum,jdbcType=INTEGER})"
    })
    int insert(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @InsertProvider(type=WarehouseSqlProvider.class, method="insertSelective")
    int insertSelective(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Select({
        "select",
        "wid, pid, uid, wprice, wnum",
        "from warehouse",
        "where wid = #{wid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="wid", property="wid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
        @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
        @Result(column="wprice", property="wprice", jdbcType=JdbcType.DECIMAL),
        @Result(column="wnum", property="wnum", jdbcType=JdbcType.INTEGER)
    })
    Warehouse selectByPrimaryKey(Integer wid);
    @Select({
            "select",
            "wid, pid, uid, wprice, wnum",
            "from warehouse",
            "where uid = #{uid,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="wid", property="wid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
            @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
            @Result(column="wprice", property="wprice", jdbcType=JdbcType.DECIMAL),
            @Result(column="wnum", property="wnum", jdbcType=JdbcType.INTEGER),
            @Result(column ="pid",property = "product",one = @One(select = "cn.Ideal.demo.dao.ProductMapper.selectByPrimaryKey"))
    })
    List<Warehouse> selectByUid(Integer uid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @UpdateProvider(type=WarehouseSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Warehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    @Update({
        "update warehouse",
        "set pid = #{pid,jdbcType=INTEGER},",
          "uid = #{uid,jdbcType=INTEGER},",
          "wprice = #{wprice,jdbcType=DECIMAL},",
          "wnum = #{wnum,jdbcType=INTEGER}",
        "where wid = #{wid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Warehouse record);

    @Select({
            "select",
            "wid, pid, uid, wprice, wnum",
            "from warehouse",
            "where pid = #{pid,jdbcType=INTEGER} and uid = #{uid,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column="wid", property="wid", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="pid", property="pid", jdbcType=JdbcType.INTEGER),
            @Result(column="uid", property="uid", jdbcType=JdbcType.INTEGER),
            @Result(column="wprice", property="wprice", jdbcType=JdbcType.DECIMAL),
            @Result(column="wnum", property="wnum", jdbcType=JdbcType.INTEGER)
    })
    Warehouse selectByUidAndPid(@Param("pid")Integer pid,@Param("uid")Integer uid);
    @Update({
            "update warehouse",
            "set pid = #{pid,jdbcType=INTEGER},",
            "uid = #{uid,jdbcType=INTEGER},",
            "wprice = #{wprice,jdbcType=DECIMAL},",
            "wnum =wnum+ #{wnum,jdbcType=INTEGER}",
            "where pid = #{pid,jdbcType=INTEGER} and uid = #{uid,jdbcType=INTEGER}"
    })
    int updateWnum(Warehouse record);
    @Update({
            "update warehouse",
            "set ",
            "wnum =wnum-#{wnum,jdbcType=INTEGER}",
            "where pid = #{pid,jdbcType=INTEGER} and uid = #{uid,jdbcType=INTEGER}"
    })
    int downWnum(Warehouse record);

    @Delete({
            "delete from warehouse",
            "where wnum <= 0"
    })
    int deleteWnum();

    @Delete({
            "delete from warehouse"
    })
    int initWarehouse();
}