package cn.Ideal.demo.dao;

import cn.Ideal.demo.entity.Warehouse;

import static org.apache.ibatis.jdbc.SqlBuilder.*;

public class WarehouseSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String insertSelective(Warehouse record) {
        BEGIN();
        INSERT_INTO("warehouse");
        
        if (record.getWid() != null) {
            VALUES("wid", "#{wid,jdbcType=INTEGER}");
        }
        
        if (record.getPid() != null) {
            VALUES("pid", "#{pid,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            VALUES("uid", "#{uid,jdbcType=INTEGER}");
        }
        
        if (record.getWprice() != null) {
            VALUES("wprice", "#{wprice,jdbcType=DECIMAL}");
        }
        
        if (record.getWnum() != null) {
            VALUES("wnum", "#{wnum,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Thu Apr 25 19:48:38 GMT+08:00 2019
     */
    public String updateByPrimaryKeySelective(Warehouse record) {
        BEGIN();
        UPDATE("warehouse");
        
        if (record.getPid() != null) {
            SET("pid = #{pid,jdbcType=INTEGER}");
        }
        
        if (record.getUid() != null) {
            SET("uid = #{uid,jdbcType=INTEGER}");
        }
        
        if (record.getWprice() != null) {
            SET("wprice = #{wprice,jdbcType=DECIMAL}");
        }
        
        if (record.getWnum() != null) {
            SET("wnum = #{wnum,jdbcType=INTEGER}");
        }
        
        WHERE("wid = #{wid,jdbcType=INTEGER}");
        
        return SQL();
    }
}